root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/backend.exe ./cmd/backend"
  bin = "tmp/backend.exe"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  delay = 500

[misc]
  clean_on_exit = true